name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  code_builder: ^4.0.0
  collection: ^1.15.0
  dart_style: ^2.0.1
  logging: ^1.0.0
  meta: ^1.1.8
  path: ^1.7.0
  quiver: ^3.0.0
  stack_trace: ^1.9.5

dev_dependencies:
  build_runner: ^1.10.1
  build_test: ^1.2.1
  inject:
    path: ../inject
  test: ^1.15.3
