name: inject.example.coffee
description: A simple example of using package:inject

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^2.0.0
  #build_web_compilers: ^1.0.0
  inject_generator:
    path: ../../package/inject_generator
  #test: ^1.0.0
